FROM phpmyadmin/phpmyadmin

LABEL maintainer="Bo-Yi Wu <gabrielfernandesfotografias@outlook.com>"

# Add volume for sessions to allow session persistence
VOLUME /sessions

# We expose phpMyAdmin on port 80
EXPOSE 80
